In [9]:
from scipy.io import wavfile
import numpy as np

In [39]:
rate, data = wavfile.read("gogo.wav")

In [51]:
maxval = (pow(2, 16) / 2) - 1

In [53]:
for i in range(0, 4):
    idx = i * rate
    val = data[idx][2]
    print(val)

8192
10922
16384
32767


In [4]:
empty = np.zeros(10, dtype=np.int16)

In [20]:
for i in range(0, 10):
    empty[i] = 100 + i

In [21]:
print(empty)

[100 101 102 103 104 105 106 107 108 109]


In [23]:
wavfile.write("1bar-metro-combined-range.wav", 44100, empty)

In [45]:
rate, data = wavfile.read("1bar-metro-combined-range.wav")

In [46]:
[data[i * 44100] for i in range(0, 4)]

[array([155, 155,   1], dtype=int16),
 array([-18, -18,   2], dtype=int16),
 array([-187, -187,    3], dtype=int16),
 array([4, 4, 4], dtype=int16)]

In [69]:
for r in [[list(range(i * 44100, i * 44100 + 512))] for i in range(0, 4)]:
    for block in r:
        for bi in block:
            data[bi][2] = data[block[0]][2]
        

In [75]:
wavfile.write("1bar-metro-combined-block.wav", 44100, data)